name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # create this at your github repository secret
          password: ${{ secrets.DOCKER_PASSWORD }} # create this at your github repository secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: src
          push: true
          tags: kubemozilla/python-app:${{ github.sha }}
